import './globals.css';

import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
import { AuthProvider } from '@/context/authContext';
import AuthGuard from '@/utils/authGuard';
import { SumProvider } from '@/components/sumContext';
export const metadata = {
  title: 'ParagonAI',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SumProvider>
      <AuthProvider>
        <html lang="en">
          <body className={inter.className}>
            <AuthGuard>{children}</AuthGuard>
          </body>
        </html>
      </AuthProvider>
    </SumProvider>
  );
}
